CREATE TABLE IF NOT EXISTS boards (
	id UUID PRIMARY KEY,
	title VARCHAR(40) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lists (
	id UUID PRIMARY KEY,
	board_id UUID NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
	title VARCHAR(30) NOT NULL,
	position INTEGER NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards (
	id UUID PRIMARY KEY,
	list_id UUID NOT NULL REFERENCES lists (id) ON DELETE CASCADE,
	title VARCHAR(80) NOT NULL,
	description VARCHAR(500) NOT NULL DEFAULT '',
	priority VARCHAR(10) NOT NULL,
	due_date DATE,
	position INTEGER NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT cards_priority_check CHECK (priority IN ('high', 'medium', 'low'))
);

CREATE INDEX IF NOT EXISTS lists_board_id_position_idx ON lists (board_id, position);
CREATE INDEX IF NOT EXISTS cards_list_id_position_idx ON cards (list_id, position);
